spring.application.name: test-adapter

#logging:
#  file: /home/agney/IdeaProjects/logs/${spring.application.name}.log
#  pattern:
#    console: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} | %level | ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} | %level | ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

camel:
  springboot:
    main-run-controller: true

incoming.from.uri: rabbitmq:in-exchange?exchangeType=headers&autoDelete=false&queue=in-queue
outgoing.to.uri: rabbitmq:out-exchange?autoDelete=false&queue=out-queue